### ISSUE TITLE
Filters dont work for ebay-kleinanzeigen

### ISSUE THREAD

**Issue by pcace** [flathunters/flathunter#46]
Hi,

since flathunter does not work for immoscout ( #45), i tried to let it hunt for flats on ebay kleinanzeigen, but realized, that filters are not recognized. 
Is this how it should be? Any other way to filter out offers with certain words?

Cheers and thanks!!!

**Comment by codders** [comment]
Filters should be working. You need to make sure your Yaml is correctly
formatted, and filter words should be all lower case.

Arthur

**Comment by codders** [comment]
Did this help at all? Can you give details of the filters you are using / what the YAML looks like?

**Comment by pcace** [comment]
Hi, sorry for not replying - i was without internet for a month;)
so i tried it again, this is the part from the config: 

```
        - https://www.ebay-kleinanzeigen.de/s-wohnung-mieten/10245/anzeige:angebote/preis::900/wohnung/k0c203l3352r10+wohnung_mieten.qm_d:80,+wohnung_mieten.zimmer_d:3,                                                                

# Define filters to exclude flats that don't meet your critera.                                                                                  
# Supported filters include 'max_rooms', 'min_rooms', 'max_size', 'min_size',                                                                
#   'max_price', 'min_price', and 'excluded_titles'.                                                                                     
#                                                                                                                                    
# 'excluded_titles' takes a list of regex patterns that match against                                                            
# the title of the flat. Any matching titles will be excluded.                                                               
# More to Python regex here: https://docs.python.org/3/library/re.html                                                   
#                                                                                                                    
# Example:                                                                                                       
# filters:                                                                                                   
#   excluded_titles:                                                                                     
#     - "wg"                                                                                         
#     - "zwischenmiete"                                                                          
#   min_price: 700                                                                           
#   max_price: 1000                                                                      
#   min_size: 50                                                                     
#   max_size: 80                                                                 
#   max_price_per_square: 1000                                               
filters:                                                                   
  excluded_titles:                                                       
    - "tausch"                                                       
    - "tauschwohnung"                                            
    - "zwischenmiete"                                        
    - "tausche"                                          
    - "tauschen"                                     
    - "gegen"                                                                                                                                                                                                                           

# There are often city districts in the address which
```

unfortunally it still not seems to work. Is there something wrong in the config?

Cheers and thanks!!!

**Comment by codders** [comment]
Nope - that should work. Please make sure you're using SPACES and not TABS in the YAML file, otherwise it might not be processed correctly.

**Comment by pcace** [comment]
hi, very strange! - i restarted the system (because of other reasons) and now it seems to be working. Sorry.
But thanks for your help!!
